config/routes.rb
Rails.application.routes.draw do
  resources :posts

  resource :bugs, only: :show

  resources :notifications do
    get :touch, on: :collection
  end

  resource :cache, only: :show

  root 'notifications#index'
end

app/models/bunny.rb
class Bunny < ActiveRecord::Base
  has_many :carrots
end

app/models/carrot.rb
class Carrot < ActiveRecord::Base
  belongs_to :bunny
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def show
    @bunny = Bunny.first
  end
end

app/controllers/caches_controller.rb
class CachesController < ApplicationController
  def show
    ActionController::Base.perform_caching = !ActionController::Base.perform_caching

    redirect_to :root
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = Notification.limit(params[:limit] || 100)
  end

  def touch
    # This will bust all the cached notification partials because a record's
    # updated_at column is part of the cache key.
    # There wouldn't be much use for this in a real app, but it's helpful to see things working.
    # Besides cache bustin' makes me feel good!
    Notification.update_all updated_at: Time.now
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: :show

  def show
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def caching_status
    if ActionController::Base.perform_caching
      'Disable caching'
    else
      'Enable caching'
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/bugs/_bunny.html.erb
<% cache bunny do %>
  <%= render bunny.carrots %>
<% end %>

app/views/bugs/show.html.erb
<%= render 'bunny', bunny: @bunny %>

app/views/carrots/_carrot.html.erb
<%# Hey, I'm a dependency %>
<%= carrot.name %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CollectionCachingTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<section class="caching-toggle">
  <%= button_to caching_status, cache_path, method: :get %>
</section>

<section class="touch-notifications">
  <%# You'll have to reload manually, like an animal! %>
  <%= button_to 'Touch notifications', touch_notifications_path, method: :get, remote: true %>
</section>

<%= yield %>

</body>
</html>

app/views/notifications/_form.html.erb
<%= form_for(notification) do |f| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/_notification.html.erb
<% cache notification do %>
  <article class="notification" id="<%= dom_id(notification) %>">
    <h1><%= notification.name %></h1> - <p><%= notification.created_at %></p>
    <p><%= notification.body %></p>
    <%# Simulate a template taking at least 30 milliseconds to render %>
    <%= sleep(0.03) %>
  </article>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All the great notifications!</h1>


<span>Limit notifications to:
<% [10, 20, 30, 50, 70, 100].each do |limit| %>
  <%= link_to limit, notifications_path(limit: limit) %> |
<% end %>
</span>

<%= render @notifications %>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>